Traceback (most recent call last):
  File "C:\Users\ee303\hanaa\test\hyper.py", line 145, in <module>
    model.fit()
  File "C:\Users\ee303\anaconda3\envs\recommenders\lib\site-packages\recommenders\models\deeprec\models\graphrec\lightgcn.py", line 258, in fit
    wandb.log({"map": map_value, "ndcg": ndcg_value, "precision": precision_value, "recall": recall_value})
NameError: name 'map_value' is not defined
Traceback (most recent call last):
  File "C:\Users\ee303\hanaa\test\hyper.py", line 145, in <module>
    model.fit()
  File "C:\Users\ee303\anaconda3\envs\recommenders\lib\site-packages\recommenders\models\deeprec\models\graphrec\lightgcn.py", line 258, in fit
    wandb.log({"map": map_value, "ndcg": ndcg_value, "precision": precision_value, "recall": recall_value})
NameError: name 'map_value' is not defined